### ISSUE TITLE
网络实现

### ISSUE THREAD

**Issue by chichuhu** [VinhLoiIT/signet-pytorch#1]
我看原论文中模型里所有的最大池化层大小都是3*3，在这个实现里都是2*2的，请问有没有试验过两种哪个性能好呢？

**Comment by VinhLoiIT** [comment]
I don't get your point. Could you please clarify it?

**Comment by chichuhu** [comment]
> I don't get your point. Could you please clarify it?

About the network implementation.
In the paper, the kernel size of all the Maxpooling layer are 3*3, and in your implementation, they are 2*2. Have you ever tested two of them, which has better performance?

**Comment by chichuhu** [comment]
> I don't get your point. Could you please clarify it?

About the network implementation.
In the paper, the kernel size of all the Maxpooling layer are 3x3, and in your implementation, they are 2x2. Have you ever tested two of them, which has better performance?

**Comment by VinhLoiIT** [comment]
Thank you for pointing it out.

I haven't tested them with the `kernel_size=(3,3)` yet that you could change the parameters to check it. I just set it to `2x2` because I think it is a "default" configuration for images.

**Comment by chichuhu** [comment]
> Thank you for pointing it out.
> 
> I haven't tested them with the `kernel_size=(3,3)` yet that you could change the parameters to check it. I just set it to `2x2` because I think it is a "default" configuration for images.

Thank you， your implementation has helped me a lot.

**Comment by VinhLoiIT** [comment]
Glad to hear that. ;)

**Comment by YourSonnet18** [comment]
> Thank you for pointing it out.
> 
> I haven't tested them with the `kernel_size=(3,3)` yet that you could change the parameters to check it. I just set it to `2x2` because I think it is a "default" configuration for images.

I tested using 3x3 on Bangali dataset, and it's better than 2x2 (acc 0.69 vs 0.73)
