### ISSUE TITLE
Network Structure fix

### ISSUE THREAD

**Issue by Andrew-Fryer** [VinhLoiIT/signet-pytorch#4]
The last layer is 256, but the SigNet paper specifies 128.
(Note: the network trains much more quickly with 128.)

**Comment by VinhLoiIT** [comment]
Thanks for pointing it out. Do you want to make a PR for this?

**Comment by Andrew-Fryer** [comment]
:+1: 
Just made this one-liner :smile_cat:

**Comment by VinhLoiIT** [comment]
It's okay. Sometimes, we don't have to do big things to contribute 😄 

Thanks for the PR.
I'll close this issue now.
